FROM python:3.8-slim

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1 

COPY . /app
# 컨테이너 내에서 코드가 실행될 경로 설정
WORKDIR /app
# requirements.txt에 명시된 필요한 packages 설치
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 5000

CMD [ "python", "main.py" ]